name: sitesathi
description: "New Horizons"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  cloud_functions: ^5.3.4
  google_places_flutter: ^2.1.0
  google_fonts: ^6.2.1
  flutter_typeahead: ^5.2.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  carousel_indicator: ^1.0.6
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/google.png
      - assets/unsplash-backdrop-1080p.jpg
      - assets/unsplash-backdrop-2400p.jpg
      - assets/unsplash-backdrop-640p.jpg
      - assets/unsplash-backdrop-full.jpg
      - assets/sthi.pdf

