// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDqauq703UU0-GakQbazEeUkH3poyfzsk',
    appId: '1:833693730476:web:23f5706654328f738e8109',
    messagingSenderId: '833693730476',
    projectId: 'sitesathi-4f0e4',
    authDomain: 'sitesathi-4f0e4.firebaseapp.com',
    storageBucket: 'sitesathi-4f0e4.firebasestorage.app',
    measurementId: 'G-CQMS0ZHJMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJy6fCbZEPbjt5gu8Yf6q0iWSKx9IIKFU',
    appId: '1:833693730476:android:dac72c073e53274d8e8109',
    messagingSenderId: '833693730476',
    projectId: 'sitesathi-4f0e4',
    storageBucket: 'sitesathi-4f0e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARxJVKj5cacg4xdvHC6ddi6NGN6PqcRAY',
    appId: '1:833693730476:ios:6fc7b6ba44280c248e8109',
    messagingSenderId: '833693730476',
    projectId: 'sitesathi-4f0e4',
    storageBucket: 'sitesathi-4f0e4.firebasestorage.app',
    androidClientId: '833693730476-a4qh0m8gkt04f8i3gg2arcpn416knn1d.apps.googleusercontent.com',
    iosClientId: '833693730476-c5slnkac5uchsdq63lb9fg1c6hjl4fqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sitesathi',
  );
}
